<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Audit Report - {{ now()->format('d M Y') }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #444; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; text-transform: uppercase; font-size: 22px; }
        .meta-info { margin-bottom: 20px; font-size: 13px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table th, .table td { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 12px; }
        .table th { background-color: #f4f4f4; font-weight: bold; text-transform: uppercase; }
        .badge { padding: 3px 7px; border-radius: 4px; font-size: 10px; font-weight: bold; color: white; }
        .bg-danger { background-color: #dc3545; }
        .bg-success { background-color: #28a745; }
        .bg-info { background-color: #17a2b8; }
        .bg-secondary { background-color: #6c757d; }
        .footer { margin-top: 30px; font-size: 11px; text-align: center; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>

    <div class="no-print" style="background: #fff3cd; padding: 10px; text-align: center; border: 1px solid #ffeeba; margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; background: #28a745; color: white; border: none; border-radius: 5px;">
            Confirm & Print Hard Copy
        </button>
    </div>

    <div class="header">
        <h1>System Security Audit Log</h1>
        <p>Regulatory Compliance & Activity Tracking Report</p>
    </div>

    <div class="meta-info">
        <table style="width: 100%;">
            <tr>
                <td><strong>Generated By:</strong> {{ auth()->user()->name }}</td>
                <td style="text-align: right;"><strong>Report Date:</strong> {{ now()->format('d/m/Y h:i A') }}</td>
            </tr>
            <tr>
                <td><strong>Status:</strong> Official System Record</td>
                <td style="text-align: right;"><strong>Total Entries:</strong> {{ count($logs) }}</td>
            </tr>
        </table>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th style="width: 15%;">Timestamp</th>
                <th style="width: 20%;">Admin/User</th>
                <th style="width: 15%;">Action Type</th>
                <th>Detailed Description of Action</th>
                <th style="width: 15%;">IP Address</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
            <tr>
                <td>
                    {{ $log->created_at->format('d/m/Y') }}<br>
                    <small>{{ $log->created_at->format('h:i:s A') }}</small>
                </td>
                <td><strong>{{ $log->user->name ?? 'SYSTEM' }}</strong></td>
                <td>
                    {{ str_replace('_', ' ', $log->action) }}
                </td>
                <td>{{ $log->description }}</td>
                <td><code>{{ $log->ip_address }}</code></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This document is an automatically generated audit trail from the Visitor Management System.</p>
        <p>End of Report - Page 1 of 1</p>
    </div>

</body>
</html>